name: PyLinter Python Linter
on: ["push"]
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Python Linter
       uses: fylein/python-pylint-github-action@v4
       with:
         source: "data_service"
         mypy-options: "--ignore-missing-imports --show-error-codes"
         pylint-options: "--rcfile=.pylintrc"
         isort-options: "-w 100",
         django: false
