name: PyLinter Python Linter
on: ["push"]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: "ubuntu-latest"
    steps:
     - uses: "actions/checkout@main"
     - name: "Python Linter"
       uses: "fylein/python-pylint-github-action@v4"
       with:
        args: "pip3 install -r requirements.txt && pylint --rcfile=.pylintrc data_service"