name: PyLinter Python Linter
on: ["push"]
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Python Linter
       uses: sunnysid3up/python-linter@master
       with:
         source: "data_service"
         mypy-options: "--ignore-missing-imports --show-error-codes"
         pylint-options: "--srcfile=.pylintrc"
         isort-options: "-w 100",
         django: false
