name: Pytest
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@main"
      - name: "Python Pytest"
        uses: "fylein/python-pytest-github-action@v1"
        with:
          args: "pip3 install -r requirements.txt && py.test"